### PR TITLE
fix: next to respect totalCount of messages returned

### LINKED ISSUE #37: prev and next links do not respect total count of messages
Prev and next link generation should query the database for the total number of matching messages.  If the current limit & offset contain the final page of messages, the next link should be null.  

Please implement this feature by creating a new Message model function to get the total count.  Assembling the links happens in the handler.  A wrapper in the MessageService layer probably makes sense to keep imports  into the handler clean.

### PR DESCRIPTION
**Pull request by Kpoke**
closes #37

### CODE REVIEW

File: server/repositories/MessageRepository.js [hunk 1]
```diff
@@ -107,6 +107,58 @@ class MessageRepository extends BaseRepository {
...
+        'survey_question',
+        'survey.id',
+        '=',
+        'survey_question.survey_id',
+      )
+      .count('*')
+      .where((builder) => whereBuilder(filter, builder));
+
+    return +result[0].count;
+  }
```
Comment (Kpoke) [inline server/repositories/MessageRepository.js:161]: @ZavenArra was not sure whether or not to include this in the getMessages due to the similarities in both of the queries

Comment (ZavenArra) [reply server/repositories/MessageRepository.js:161]: I think you could create an internal function in the repo that returns the main body of the query, and call that from the two functions, which then apply the customizations for either getting a range or records or the total count.  The would be right way to factor this logic as a unit.

**Review by ZavenArra — CHANGES_REQUESTED** [review]
I think refactoring the repository such that query logic can be shared between the two function calls should be done.
